---
- name: Get System Inventory
  hosts: baremetal
  connection: local
  gather_facts: false
  tasks:
    - name: Imclude Dell DRAC discovery role
      ansible.builtin.include_role:
        name: drac-discovery
      vars:
        drac_discovery_hostname: "{{ inventory_hostname }}"
        drac_discovery_username: "{{ oob_username }}"
        drac_discovery_password: "{{ oob_password }}"
        drac_discovery_role: master
        drac_discovery_clustername: example1
        drac_discovery_ipaddress: "{{ oob_ipaddr }}"
        drac_discovery_credentials: "{{ drac_discovery_clustername }}-drac-credentials"
        drac_discovery_boot_device: "{{ boot_device }}"
        # drac_discovery_macaddress: "{{ boot_macaddr }}"
...